### ISSUE TITLE
Great idea!

### ISSUE THREAD

**Issue by rhysr** [scottasmith/schemaroller#1]
OMG! Where did you come up with this idea?

;)

**Comment by adam-ja** [comment]
I look forward to seeing the finished product, seems like something we could use at work.

**Comment by tvking** [comment]
![801856a4851091790942396096512_291d5660a36 0 4](https://cloud.githubusercontent.com/assets/4874892/12414172/a1f4a10a-be8b-11e5-96b5-641f24d818ac.jpg)

**Comment by rhysr** [comment]
BOOOOO!!!

**Comment by scottasmith** [comment]
Oh I miss the wit.....NOT!

I'm wanting to create an independent simple roller module as I need it for the work I'm doing.

**Comment by rhysr** [comment]
Awww Scoooooot, we miss you!

**Comment by scottasmith** [comment]
I miss being able to access all your systems.... Oh, wait I still can! (I **don't** but can)
